// Generated by scripts/package-paykit-context.js; do not edit.
export const PAYKIT_IMAGE_MANIFEST_SHA256 =
  'd67c91daae1525375153db11b640239c843b55ae73a193b9ca4f93507a62320d';
export const PAYKIT_IMAGE_CONTEXT_SHA256 =
  'd2192f070b80d898758d3b455bfe5da5d01c6573a7c6add50ab4944540a7550e';
export const PAYKIT_IMAGE_TAG = 'polar-paykit/service:4.0.0-d2192f070b80d898';
