// Generated by scripts/package-paykit-context.js; do not edit.
export const PAYKIT_IMAGE_MANIFEST_SHA256 =
  '6a6dd0907522073659539054a150ef6a6d410d83e4023f6bd16d16fb29e3a7e9';
export const PAYKIT_IMAGE_CONTEXT_SHA256 =
  'fa74e12d7f4de98774afea0d40cbd6e08fd8a9bb67448d2f33f84b98eec661f6';
export const PAYKIT_IMAGE_TAG = 'polar-paykit/service:4.0.0-fa74e12d7f4de987';
