// Generated by scripts/package-paykit-context.js; do not edit.
export const PAYKIT_IMAGE_MANIFEST_SHA256 =
  '302c741c24125f0be0883ed9f1ad173a466c9b5c5f8eb682702fc58747fa793f';
export const PAYKIT_IMAGE_CONTEXT_SHA256 =
  '65ffe644370826b9786568da754d75229ec335a98606e65f9785bded90bd1c6a';
export const PAYKIT_IMAGE_TAG = 'polar-paykit/service:4.0.0-65ffe644370826b9';
